name: Deploy to Render
on:
    push:
        branches:
            - main
        paths:
            - www/**/*.*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Do nothing
              run: echo "I assume all webpack builds finished before deployment."
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Don't test anything
              run: echo 'WARN - No test specified.'
    deploy:
        environment: render
        runs-on: ubuntu-latest
        steps:
            - name: Notify Render about new commit
              run: curl ${{ secrets.RENDER_HOOK_URL }}